### ISSUE TITLE
网易生活小程序还是不行

### ISSUE THREAD

**Issue by SingTsang** [CHERWING/CHERWIN_SCRIPTS#11]
![screenshot-1715688537399](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/21009275/79984423-2aa0-4b50-a591-cc93ca705d83)

**Comment by CHERWING** [comment]
需要抓绑定手机后的变量

**Comment by SingTsang** [comment]
> 需要抓绑定手机后的变量

初次微信登陆就已经绑定了手机号了，而且我抓的token是qB2开头的，和你的完全不一样
