### ISSUE TITLE
999会员中心报ssl错误

### ISSUE THREAD

**Issue by yang7758258** [CHERWING/CHERWIN_SCRIPTS#22]
![image](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/43715693/dc55cde6-0fcb-485b-ad8a-c870e6f60779)

**Comment by SingTsang** [comment]
本子没问题，可以跑，openssl.cnf需要修改一下

**Comment by yang7758258** [comment]
> 本子没问题，可以跑，openssl.cnf需要修改一下 ![IMG_3067](https://private-user-images.githubusercontent.com/21009275/333287130-6c9cd8b4-0742-4e72-8912-4eff47b88a88.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MjMwNDMsIm5iZiI6MTcxNjUyMjc0MywicGF0aCI6Ii8yMTAwOTI3NS8zMzMyODcxMzAtNmM5Y2Q4YjQtMDc0Mi00ZTcyLTg5MTItNGVmZjQ3Yjg4YTg4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwMzUyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjlmMGI2MTQ2NmM1ZmQ3YTc2NTQxNzM1N2I1MGNlYWE1NTUzOGVmZWM2ZTliNThlYjg1ZDFmN2M2YWU2OTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pD1Zy5fwvaZBouhk3xzTtrFBmLgHji8gpT6Y8vJfDSE)

这个在哪里修改呢

**Comment by CHERWING** [comment]
测试没问题，检查下自己环境
