### ISSUE TITLE
999会员中心小程序

### ISSUE THREAD

**Issue by pp2120** [CHERWING/CHERWIN_SCRIPTS#23]
>>>>>>开始获取版本信息...
当前检测：【CHERWIN_TOOLS.py】
本地版本：【2024.05.23】
服务器版本：【2024.05.23】
无需更新

当前检测：【JJJHYZX.py】
本地版本：【2024.05.24】
服务器版本：【2024.05.24】
无需更新

>>>>>>>>>>共获取到1个账号<<<<<<<<<<

开始执行第1个账号--------------->>>>>

====== 用户信息 ======
请求异常❌： HTTPSConnectionPool(host='mc.999.com.cn', port=443): Max retries exceeded with url: /zanmall_diy/ma/personal/user/info (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)')))
Traceback (most recent call last):
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/JJJHYZX.py", line 326, in <module>
    run_result = RUN(infos, index).main()
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/JJJHYZX.py", line 207, in main
    if self.get_userinfo():
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/JJJHYZX.py", line 96, in get_userinfo
    if response.get('success', False):
AttributeError: 'NoneType' object has no attribute 'get'

## 执行结束...   耗时 3 秒　　　　　
还是这样青龙2.15.15

**Comment by CHERWING** [comment]
> > > > > > > 开始获取版本信息...
> > > > > > > 当前检测：【CHERWIN_TOOLS.py】
> > > > > > > 本地版本：【2024.05.23】
> > > > > > > 服务器版本：【2024.05.23】
> > > > > > > 无需更新
> 
> 当前检测：【JJJHYZX.py】 本地版本：【2024.05.24】 服务器版本：【2024.05.24】 无需更新
> 
> > > > > > > > > > > 共获取到1个账号<<<<<<<<<<
> 
> 开始执行第1个账号--------------->>>>>
> 
> ====== 用户信息 ====== 请求异常❌： HTTPSConnectionPool（host='mc.999.com.cn'， port=443）： 超出最大重试次数，网址： /zanmall_diy/马/personal/user/info （Caused by SSLError（SSLError（1， '[SSL： UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled （_ssl.c：1007）'））） 回溯（最近一次调用）：文件“/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/JJJHYZX.py”，第 326 行，在 run_result = RUN（infos， index）.main（）文件“/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/JJJHYZX.py”，第 207 行，主 if self.get_userinfo（）： 文件“/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS/JJJHYZX.py”，第 96 行，在 get_userinfo if response.get（'success'， False）： AttributeError： 'NoneType' 对象没有属性 'get'
> 
> ## 执行结束...耗时 3 秒
> 还是这样青龙2.15.15

999已更新，需要[搭建反代](https://github.com/CHERWING/CHERWIN_SCRIPTS/tree/main/Cloudflare%20Workers%20Proxy)

**Comment by xiaohongmao1** [comment]
请问我该怎么用这个程序？
