### ISSUE TITLE
春茧未来荟

### ISSUE THREAD

**Issue by pp2120** [CHERWING/CHERWIN_SCRIPTS#29]
应用名称：春茧未来荟小程序
  任务奖励：999系列的，签到有积分。

**Comment by gsjz20** [comment]
> 应用名称：春茧未来荟小程序 任务奖励：999系列的，签到有积分。

就只有积分，并且积分不能兑换请问这个积分签到了有什么用呢

**Comment by pp2120** [comment]
跟华润通是一起，可以对红包，e卡

**Comment by CHERWING** [comment]
已采纳，已发布脚本，感谢投稿

**Comment by zheshi111** [comment]
华润系列还有：润生活小程序，积分也是通用的
