### ISSUE TITLE
TYQH_JK.py卡住，跑不了

### ISSUE THREAD

**Issue by wannian20** [CHERWING/CHERWIN_SCRIPTS#3]
青龙版本2.14.8，在获取到账号账号之后就卡住不动了
![Screenshot_2024-05-05-19-24-18-35_b82a250edd84722a62895b044910a9a7](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/59636417/d6193171-5e30-4114-a022-f0abbcf6c738)

**Comment by yang7758258** [comment]
+1

**Comment by CHERWING** [comment]
服务器崩溃导致，已修复

**Comment by wannian20** [comment]
试了还是卡住

**Comment by yang7758258** [comment]
+1发自我的 iPhone在 2024年5月9日，13:36，wannian20 ***@***.***> 写道：﻿
试了还是卡住
