### ISSUE TITLE
安慕希

### ISSUE THREAD

**Issue by zheshi111** [CHERWING/CHERWIN_SCRIPTS#30]
安慕希小程序：每周五抽奖，右边悬浮窗瓜分5555瓶酸奶，一直到7月才结束
老板电器服务微商城小程序：任务的积分兑换东西

**Comment by CHERWING** [comment]
> 安慕希小程序：每周五抽奖，右边悬浮窗瓜分5555瓶酸奶，一直到7月才结束 老板电器服务微商城小程序：任务的积分兑换东西

感谢反馈，已采纳。老板电器已完成，安慕希要等下周五看看

**Comment by zheshi111** [comment]
老板，周五了，安慕希抽奖
