### ISSUE TITLE
活力伊利的source貌似不太对

### ISSUE THREAD

**Issue by taurus2146** [CHERWING/CHERWIN_SCRIPTS#32]
抓包拿到活力伊利的token,程序运行时显示source是1577,但是脚本里面是1520,我试着改了下脚本把预置的那个1520修改为1577之后,活力伊利是能正常运行的,想问下是脚本里面的活力伊利的source不对还是我的小程序和作者您的不是同一个小程序?(小程序名字就叫活力伊利)
![image](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/4773894/9709dc81-9305-4cfb-a788-8cd42d1ebf2b)

**Comment by CHERWING** [comment]
> 抓包拿到活力伊利的token,程序运行时显示source是1577,但是脚本里面是1520,我试着改了下脚本把预置的那个1520修改为1577之后,活力伊利是能正常运行的,想问下是脚本里面的活力伊利的source不对还是我的小程序和作者您的不是同一个小程序?(小程序名字就叫活力伊利) ![image](https://private-user-images.githubusercontent.com/4773894/335923723-9709dc81-9305-4cfb-a788-8cd42d1ebf2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MzQxMTEsIm5iZiI6MTcxNzUzMzgxMSwicGF0aCI6Ii80NzczODk0LzMzNTkyMzcyMy05NzA5ZGM4MS05MzA1LTRjZmItYTc4OC04Y2Q0MmQxZWJmMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDRUMjA0MzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM1Njg5NzI4MGJkNGRjM2I3NTQyNjA5YjgwMGFjY2Q3ODZkZWJlYzkwMmQ0NDY1YWJhY2U5OWQ3MGM4ZDExOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SaBT2vb-iOqknmfYFz0qufLKwXhqOi0VftX32BJhcok)

已更新，这个source新注册用户和之前的不一样 后面看看能不能动态获取
