### ISSUE TITLE
春茧未来荟小程序

### ISSUE THREAD

**Issue by pp2120** [CHERWING/CHERWIN_SCRIPTS#34]
===== 获取用户信息 ======
请求异常❌： HTTPSConnectionPool(host='program.springcocoon.com', port=443): Max retries exceeded with url: /szbay/api/services/app/CRCWeixinEmpMerge/QueryMergeDataAsync (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)')))
Traceback (most recent call last):
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS_main/CJWLH.py", line 303, in <module>
    run_result = RUN(infos, index).main()
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS_main/CJWLH.py", line 189, in main
    if self.get_user_info():
  File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS_main/CJWLH.py", line 110, in get_user_info
    if response.get('result', False) != False:
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by gsjz20** [comment]
正常的 都是一样

**Comment by CHERWING** [comment]
> ===== 获取用户信息 ====== 请求异常❌： HTTPSConnectionPool(host='program.springcocoon.com', port=443): Max retries exceeded with url: /szbay/api/services/app/CRCWeixinEmpMerge/QueryMergeDataAsync (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)'))) Traceback (most recent call last): File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS_main/CJWLH.py", line 303, in run_result = RUN(infos, index).main() File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS_main/CJWLH.py", line 189, in main if self.get_user_info(): File "/ql/data/scripts/CHERWING_CHERWIN_SCRIPTS_main/CJWLH.py", line 110, in get_user_info if response.get('result', False) != False: AttributeError: 'NoneType' object has no attribute 'get'

已更新，需要反代域名
