### ISSUE TITLE
ZTKD token一直失效问题

### ISSUE THREAD

**Issue by z6135** [CHERWING/CHERWIN_SCRIPTS#5]
开始执行第1个账号--------------->>>>>
>>>>>>获取积分信息
可能token失效了
中通快递小程序挂机通知

>>>>>>获取积分信息
可能token失效了

***********@Cherwin************

**Comment by CHERWING** [comment]
测试过没问题，请确认提取的token是否正确

**Comment by z6135** [comment]
需要进入到签到详情里面，抓取token，，x-token 会一直提示失效问题。
