### ISSUE TITLE
朴朴闪退

### ISSUE THREAD

**Issue by johnzon520** [CHERWING/CHERWIN_SCRIPTS#53]
朴朴雷电9.0.73模拟器闪退，请问有不闪退推荐的模拟器版本吗，谢谢大神。

**Comment by xueba0458** [comment]
没有已经root的手机吗？

**Comment by johnzon520** [comment]
> 没有已经root的手机吗？ @johnzon520

没有😂

**Comment by johnzon520** [comment]
> 没有已经root的手机吗？ @johnzon520

找了个root手机，打开xp框架就闪退，各种隐藏还是闪退，禁用框架就正常，大神请问还有其他方法可以抓pupu token吗？

**Comment by xueba0458** [comment]
@johnzon520 果然一hook就闪退😢😢😢😢😢

**Comment by xueba0458** [comment]
@johnzon520 最新进展，使用肉丝大佬的脚本成功无视ssl抓包
![image](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/51258772/34875d8e-1048-4d21-bf26-b3710969f649)

**Comment by xueba0458** [comment]
@johnzon520 去豌豆荚下载旧版4.7.3，新版的接口根本抓不到refresh_token
![image](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/51258772/da9e0b6c-7cad-4a07-bf1a-b47c4d3bac31)
![image](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/51258772/6d18abd1-b51c-4362-ba41-31f882af937e)

**Comment by johnzon520** [comment]
@xueba0458   感谢大佬指点，但是肉丝大佬的脚本运行有点问题
frida-ps -H 127.0.0.1:51234  显示进程正常，但是python r0capture.py -H 127.0.0.1:51234 报错，麻烦大佬具体请看图片信息
![微信截图_20240706174336](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/46586257/2009fcb4-9c55-4615-99a2-cf47c843aab8)
![微信截图_20240706174457](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/46586257/31d3c930-9d97-42c5-93a4-edae6ef3bee3)

**Comment by xueba0458** [comment]
@johnzon520 包名前面少敲了-f
-H指定远程地址
-f指定包名....
犯了低级错误
![image](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/51258772/e5865d23-75c1-4499-96b1-e87bd04d9122)
![image](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/51258772/7568fa69-562f-42b0-817f-ad9600c78c8c)

**Comment by sola237** [comment]
@xueba0458 你好 想用问下Frida 和objection抓包 是不是需要有个root的手机，root的安卓模拟器可以吗

**Comment by xueba0458** [comment]
> @xueba0458 你好 想用问下Frida 和objection抓包 是不是需要有个root的手机，root的安卓模拟器可以吗

安卓模拟器也可以，不一定是真机

**Comment by johnzon520** [comment]
@xueba0458  感谢。现在不管是肉丝的脚本还是objeciton，一运行命令，APP就自动重启，奇怪了，APP也是下载你说的那个版本。
![微信截图_20240708104737](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/46586257/8008f41f-680b-4b0c-ba65-cd35e0b238cd)
![微信截图_20240708104803](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/46586257/db5245fa-8363-473b-a082-46667d4efcb9)

**Comment by johnzon520** [comment]
注入meituan 正常，估计还是ppcs有反抓限制
![微信截图_20240708123001](https://github.com/CHERWING/CHERWIN_SCRIPTS/assets/46586257/47623735-8aaa-4426-8ac7-101b4d13f5eb)

**Comment by xueba0458** [comment]
@johnzon520 frida用最新版就行了，没必要用推荐的版本。闪退是因为被检测到了，手机上运行./fridaxxxxxx -l 0.0.0.0:10003(这里的端口随机，确保你不是使用的默认端口)电脑端运行肉丝大佬的脚本并使用手机的ip地址加端口号就行了

**Comment by sola237** [comment]
@xueba0458 肉丝大佬的脚本能推荐下地址吗~我没有用过frida 得去搜下= =

**Comment by xueba0458** [comment]
@sola237 https://github.com/r0ysue/r0capture.git

**Comment by sola237** [comment]
@xueba0458 感谢  我去学下怎么使用，最近这个朴朴超市的包太难抓了，苹果steam也抓不出来

**Comment by johnzon520** [comment]
已解决

**Comment by johnzon520** [comment]
@xueba0458  感谢大佬，问题已解决。

**Comment by sola237** [comment]
@johnzon520 用模拟器抓低版本+肉丝大佬的脚本吗

**Comment by xueba0458** [comment]
@sola237 我用的真机，没用模拟器抓，但是你可以试试

**Comment by johnzon520** [comment]
@sola237  真机+frida objection +BurpSuite。模拟器用不了，闪退。

**Comment by sola237** [comment]
啊好吧 没有root了的安卓机，今天在装模拟器和frida，不行那暂时就不折腾了。能整个可以返回refresh_token的朴朴超市app吗？

**Comment by xueba0458** [comment]
@sola237 我试了很多旧版本，发现其实旧版的朴朴应该是有概率绕过检测的(今年开始的版本才对检测进行了加强，具体是多久忘了，比如对lsp等框架的检测就加强了），但是前提是你能绕过更新弹窗……

模拟器能否打开朴朴，就看你能否隐藏环境绕过检测了(可以试试用magisk+改机型模块，我电脑配置不行，没办法测试模拟器）。

当然如果有能力，你也可以想办法可以直接逆向朴朴。

**Comment by sola237** [comment]
@xueba0458 有点难度  frida都是现学的…
隐藏环境倒是可以试试，如果是有强制更新弹窗，那就无解了
不在我能解决的范畴内…
