### ISSUE TITLE
>>>>>>>开始获取版本信息... 获取CHERWIN_SCRIPT_CONFIG.json失败

### ISSUE THREAD

**Issue by wzgrx** [CHERWING/CHERWIN_SCRIPTS#58]
>>>>>>>开始获取版本信息...
获取CHERWIN_SCRIPT_CONFIG.json失败

**Comment by xueba0458** [comment]
@wzgrx 发issue之前，记得先看看有没有其他用户已经发过了....
https://github.com/CHERWING/CHERWIN_SCRIPTS/issues/50
