### ISSUE TITLE
解决中通打开小程序后token需要重新抓的问题

### ISSUE THREAD

**Issue by huzige433** [CHERWING/CHERWIN_SCRIPTS#9]
import requests
url = "https://hdgateway.zto.com/getZkuaiMediaToken"
headers = {
    "Host": "hdgateway.zto.com",
    "Connection": "keep-alive",
    "Content-Length": "0",
    "charset": "utf-8",
    "x-oid": "*****",
    "x-sv-v": "0.22.0",
    "x-token": "*****这里是app的token",
    "x-clientcode": "wechatMiniZtoHelper",
    "User-Agent": "User-Agent",
    "content-type": "application/json",
    "x-version": "V8.22.0",
    "x-ys-dt": "a92c8046a6284*****",
    "Referer": "https://servicewechat.com/wx7ddec*****/444/page-frame.html"
}
response = requests.request("POST", url, headers=headers)
print(response.text)

***我隐藏掉了我的敏感信息
用这段可以获取h5页面的token,这样可以不需要每次打开小程序h5页面旧又要重新抓token了

**Comment by CHERWING** [comment]
感谢反馈， 找https://api.ztomember.com/api/user/point/get请求头里的短的[token]，这个token重新打开小程序不会失效
